version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${WEB_SERVER_PORT:-8000}:80'
        depends_on:
            - php-fpm
            - redis

    php-fpm:
        build: 
          context: .
          dockerfile: docker/php-fpm/Dockerfile
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/php.ini'
            - './docker/nginx/error.log:/var/log/nginx/application_php_errors.log'
        command: sh -c "composer install && php-fpm"
        depends_on:
            - redis

    redis:
        image: redis:alpine
